services:
  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend/src/:/app/src/
      - ./frontend/public/:/app/public
      - ./frontend/index.html/:/app/index.html
      - ./frontend/vite.config.ts/:/app/vite.config.ts
      - ./frontend/tailwind.config.js/:/app/tailwind.config.js
  backend:
    build: ./backend
    ports:
      - 4000:4000
    env_file:
      - ./backend/backend.env
    volumes:
      - ./backend/src/:/app/src
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: thegoodcorner
      POSTGRES_DB: thegoodcorner
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
    driver: local
