GET http://localhost:3000/tags
###
GET http://localhost:3000/tags/3
###

POST  http://localhost:3000/tags
Content-Type: application/json

{
    "title": "Objet Rare"
    
}

###
PUT http://localhost:3000/tags/4
Content-Type: application/json

{
    "title": "Vélo"
}
###
PATCH http://localhost:3000/tags/3
Content-Type: application/json

{
    "title":"Rolers",
    "description":"Super Rolers fast as f boiiiii"

}
###
DELETE  http://localhost:3000/tags/2


